### ISSUE TITLE
Explore time filters, time series data, and options

### ISSUE THREAD

**Issue by colearendt** [snakedotdev/grafana-duckdb-datasource#17]
The Postgres Grafana plugin uses a `time` field. We mostly moved that boilerplate across - perhaps we should add `ts` as a field option? Or create a UX component that displays the time field selection?

The latter might be tricky since all of the UI is all in the QueryBuilder ui component...

We want to make sure Grafana can visualize and display the data well!!

**Comment by wearpants** [comment]
I don't think this is necessary, grafana seemed to detect the proper x-axis time field automagically (`ts in my example DB), and source databases could have any possible schema... we can tell users they need to alias columns if necessary
