### ISSUE TITLE
Switch off of adhoc npm repository

### ISSUE THREAD

**Issue by colearendt** [snakedotdev/grafana-duckdb-datasource#2]
https://github.com/snakedotdev/grafana-duckdb-datasource/blob/4214589190a49d1e8ec64a6ba5dab1af4b177b73/.github/workflows/ci.yml#L58

We need to figure out what longer-term npm repository we want to use. Grafana does not publish many of their packages for the SQL building (they are considered "experimental" and published to `npm`, but presumably access controlled). As a result, we have published these versions manually to our own npm repo.

We should figure out what a longer term pattern looks like!

Also worth noting that we are installing pre-release versions of these packages, so we should probably keep an eye on changes and whatnot for integration!

**Comment by colearendt** [comment]
Plan to replace this in the short term is to build (and script) a verdaccio install that can be used in lieu of the adhoc / stateful instance currently in use.

**Comment by colearendt** [comment]
Script in progress:

```
docker run -p 4873:4873 -it --rm -v /Users/colearendt/src/github.com/benetist/benetist-kubernetes/verd-config.yaml:/verdaccio/conf/config.yaml verdaccio/verdaccio:6.0.0
npm add-user --registry http://localhost:4873


git clone https://github.com/grafana/grafana.git # fbad76007d88490d04b1bcf087ffaa0cd0c04a23

# not necessary
# git clone https://github.com/grafana/grafana-experimental.git # 2be55e755e99e06ed7971ee792a3616859b537b3

cd grafana/packages/grafana-data && npm publish --registry http://localhost:4873
cd ../
cd grafana-ui && npm publish --registry http://localhost:4873
cd ../
cd grafana-e2e-selectors && npm publish --registry http://localhost:4873
cd ../
cd grafana-runtime && npm publish --registry http://localhost:4873
cd ../
cd grafana-schema && npm publish --registry http://localhost:4873
cd ../
cd grafana-sql/ && sed -i '' 's/"private".*,//g' package.json && npm publish --registry http://localhost:4873

```

**Comment by wearpants** [comment]
@colearendt This is the major blocker to reproducible builds / shipping

**Comment by colearendt** [comment]
This is very nearly done. Wanted to get your thoughts about best next step though:

- I built a multi-arch container (arm and amd) so that we could have it running in CI. I probably could have used emulation but 🤷 
- running the docker container / npm repository in the CI builds turned out to be sorta flaky and hard to debug
- I switched to running the container on fly.io, and that was much easier to debug
- I can try to go back to running the container in CI if you'd like, but it seems like a less-than-ideal setup

What are your thoughts on running something on fly.io instead of in the build process? Pretty easy to set it up if you want to own, or I can create you an org or something - the `.toml` file is in the repo

**Comment by colearendt** [comment]
This is done - we deployed to `fly.io` - it is pretty easy to deploy yourself, although it is also reproducible and running at little-to-no cost in my account at present. The image itself is pushed to this repository: https://github.com/users/colearendt/packages/container/package/grafana-duckdb-datasource-npm

Happy to push elsewhere, but it is multi-arch and annoying to transfer between repositories as a result.
